### ISSUE TITLE
TASK-App_testing

### ISSUE THREAD

**Issue by s1hu** [Rebooting-Me/Home-Maintainence-Service#121]
Carry out a comprehensive integration test of the CasaCare SPA

## Test results:

- `About` and `Contact` are inactive.
- _Back_ and _Refreshing_ always takes you to the Dashboard irrespective of the state of the application.
### Homeowner Side:
- For no CO profiles, when HO selects to view their profiles, the card view is not viable.
- Also, clicking that 'more...' card directs you to an empty page with the heading 'Loading'.
- For multiple empty CO profiles, it shows multiple 'more...' cards which all redirect to the 'Loading' empty page.
### Contractor Side:

- The personal website link on the profile page is not type-proof i.e. it doesn't check the URL pattern and redirects strings without standard `http` and `https` formats.
- For a CO not owning a personal website, there is no _N.A._ option to choose.
- Assuming incorporation of _N.A._ option, there is no functionality yet to not show the URL on the active tab.
- On redirection to a HO stand-alone listing, the back button says 'view all your projects' which should not be the case as CO doesn't have any of his projects.

**Comment by Rebooting-Me** [comment]
In effect of our last discussion regarding these tests, I will be closing this task as our application is now all set for presentation.
