### ISSUE TITLE
Task: Login/Signin for Users

### ISSUE THREAD

**Issue by Rebooting-Me** [Rebooting-Me/Home-Maintainence-Service#23]
**Description:**

This is a task which comprises sub-tasks which eventually finalize the login page of the application for both end users and connect them to their respective dashboards.

**TASKS:**

- Login/sign-in UI (45 min)
- Form validation (30 min)
- DB info Validation (30 min)
- Connect to User Stories 13 and 14 (dashboards) (15 min)
- Session checks/management (30 min)
- Write tests (45 min)
- Pass tests (45 min)

**Comment by s1hu** [comment]
Finished during 1st sprint.
